version: '3.8'

services:
    client-app:
        build: ./pbs_client
        expose:
        - "5000"


    nginx:
        image: nginx:alpine
        ports:
        - "80:80"
        volumes:
        - ./pbs_client/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - client-app

    backend-app:
        build: ./pbs_backend
        volumes:
        - ./pbs_backend:/usr/src/app
        env_file:
        - .env
        depends_on:
        - db
        command: sh -c "node ace migration:run && node bin/server.js"

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PORT: ${DB_PORT}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
