version: '3.8'

services:
    client-app:
        build: ./pbs_client
        env_file:
        - .env
        expose:
        - "5000"

    backend-app:
        build: ./pbs_backend
        volumes:
        - ./pbs_backend:/usr/src/app
        env_file:
        - .env
        expose:
            - ${PORT}
        depends_on:
        - db
        command: sh -c "node ace migration:run && node ace db:seed && node bin/server.js"

    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PORT: ${DB_PORT}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
        # - ./export_202407301223.sql:/docker-entrypoint-initdb.d/export_202407301223.sql
        - postgres-data:/var/lib/postgresql/data

    nginx:
        image: nginx:alpine
        ports:
        - "80:80"
        volumes:
        - ./pbs_client/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - client-app
        - backend-app

volumes:
    postgres-data:
